#include "job.h"

#include "../../job.h"

void luaopen_job(lua_State *L)
{
    lua_createtable(L, 0, 81);
    lua_pushinteger(L, JOB_BEGINNER);
    lua_setfield(L, -2, "BEGINNER");
    lua_pushinteger(L, JOB_SWORDSMAN);
    lua_setfield(L, -2, "SWORDSMAN");
    lua_pushinteger(L, JOB_FIGHTER);
    lua_setfield(L, -2, "FIGHTER");
    lua_pushinteger(L, JOB_CRUSADER);
    lua_setfield(L, -2, "CRUSADER");
    lua_pushinteger(L, JOB_HERO);
    lua_setfield(L, -2, "HERO");
    lua_pushinteger(L, JOB_PAGE);
    lua_setfield(L, -2, "PAGE");
    lua_pushinteger(L, JOB_WHITE_KNGIHT);
    lua_setfield(L, -2, "WHITE_KNIGHT");
    lua_pushinteger(L, JOB_PALADIN);
    lua_setfield(L, -2, "PALADIN");
    lua_pushinteger(L, JOB_SPEARMAN);
    lua_setfield(L, -2, "SPEARMAN");
    lua_pushinteger(L, JOB_BERSERKER);
    lua_setfield(L, -2, "BERSERKER");
    lua_pushinteger(L, JOB_DARK_KNGIHT);
    lua_setfield(L, -2, "DARK_KNIGHT");
    lua_pushinteger(L, JOB_MAGICIAN);
    lua_setfield(L, -2, "MAGICIAN");
    lua_pushinteger(L, JOB_FIRE_WIZARD);
    lua_setfield(L, -2, "FIRE_WIZARD");
    lua_pushinteger(L, JOB_FIRE_MAGE);
    lua_setfield(L, -2, "FIRE_MAGE");
    lua_pushinteger(L, JOB_FIRE_ARCH_MAGE);
    lua_setfield(L, -2, "FIRE_ARCH_MAGE");
    lua_pushinteger(L, JOB_ICE_WIZARD);
    lua_setfield(L, -2, "ICE_WIZARD");
    lua_pushinteger(L, JOB_ICE_MAGE);
    lua_setfield(L, -2, "ICE_MAGE");
    lua_pushinteger(L, JOB_ICE_ARCH_MAGE);
    lua_setfield(L, -2, "ICE_ARCH_MAGE");
    lua_pushinteger(L, JOB_CLERIC);
    lua_setfield(L, -2, "CLERIC");
    lua_pushinteger(L, JOB_PRIEST);
    lua_setfield(L, -2, "PRIEST");
    lua_pushinteger(L, JOB_BISHOP);
    lua_setfield(L, -2, "BISHOP");
    lua_pushinteger(L, JOB_ARCHER);
    lua_setfield(L, -2, "ARCHER");
    lua_pushinteger(L, JOB_HUNTER);
    lua_setfield(L, -2, "HUNTER");
    lua_pushinteger(L, JOB_RANGER);
    lua_setfield(L, -2, "RANGER");
    lua_pushinteger(L, JOB_BOW_MASTER);
    lua_setfield(L, -2, "BOW_MASTER");
    lua_pushinteger(L, JOB_CROSSBOWMAN);
    lua_setfield(L, -2, "CROSSBOWMAN");
    lua_pushinteger(L, JOB_SNIPER);
    lua_setfield(L, -2, "SNIPER");
    lua_pushinteger(L, JOB_MARKSMAN);
    lua_setfield(L, -2, "MARKSMAN");
    lua_pushinteger(L, JOB_ROGUE);
    lua_setfield(L, -2, "ROGUE");
    lua_pushinteger(L, JOB_ASSASSIN);
    lua_setfield(L, -2, "ASSASSIN");
    lua_pushinteger(L, JOB_HERMIT);
    lua_setfield(L, -2, "HERMIT");
    lua_pushinteger(L, JOB_NIGHT_LORD);
    lua_setfield(L, -2, "NIGHT_LORD");
    lua_pushinteger(L, JOB_BANDIT);
    lua_setfield(L, -2, "BANDIT");
    lua_pushinteger(L, JOB_CHIEF_BANDIT);
    lua_setfield(L, -2, "CHIEF_BANDIT");
    lua_pushinteger(L, JOB_SHADOWER);
    lua_setfield(L, -2, "SHADOWER");
    lua_pushinteger(L, JOB_PIRATE);
    lua_setfield(L, -2, "PIRATE");
    lua_pushinteger(L, JOB_BRAWLER);
    lua_setfield(L, -2, "BRAWLER");
    lua_pushinteger(L, JOB_MARAUDER);
    lua_setfield(L, -2, "MARAUDER");
    lua_pushinteger(L, JOB_BUCCANEER);
    lua_setfield(L, -2, "BUCCANEER");
    lua_pushinteger(L, JOB_GUNSLINGER);
    lua_setfield(L, -2, "GUNSLINGER");
    lua_pushinteger(L, JOB_OUTLAW);
    lua_setfield(L, -2, "OUTLAW");
    lua_pushinteger(L, JOB_CORSAIR);
    lua_setfield(L, -2, "CORSAIR");
    lua_pushinteger(L, JOB_GM);
    lua_setfield(L, -2, "GM");
    lua_pushinteger(L, JOB_SUPER_GM);
    lua_setfield(L, -2, "SUPER_GM");
    lua_pushinteger(L, JOB_NOBLESSE);
    lua_setfield(L, -2, "NOBLESSE");
    lua_pushinteger(L, JOB_DAWN_WARRIOR);
    lua_setfield(L, -2, "DAWN_WARRIOR");
    lua_pushinteger(L, JOB_DAWN_WARRIOR_1);
    lua_setfield(L, -2, "DAWN_WARRIOR_1");
    lua_pushinteger(L, JOB_DAWN_WARRIOR_2);
    lua_setfield(L, -2, "DAWN_WARRIOR_2");
    lua_pushinteger(L, JOB_DAWN_WARRIOR_3);
    lua_setfield(L, -2, "DAWN_WARRIOR_3");
    lua_pushinteger(L, JOB_BLAZE_WIZARD);
    lua_setfield(L, -2, "BLAZE_WIZARD");
    lua_pushinteger(L, JOB_BLAZE_WIZARD_1);
    lua_setfield(L, -2, "BLAZE_WIZARD_1");
    lua_pushinteger(L, JOB_BLAZE_WIZARD_2);
    lua_setfield(L, -2, "BLAZE_WIZARD_2");
    lua_pushinteger(L, JOB_BLAZE_WIZARD_3);
    lua_setfield(L, -2, "BLAZE_WIZARD_3");
    lua_pushinteger(L, JOB_WIND_ARCHER);
    lua_setfield(L, -2, "WIND_ARCHER");
    lua_pushinteger(L, JOB_WIND_ARCHER_1);
    lua_setfield(L, -2, "WIND_ARCHER_1");
    lua_pushinteger(L, JOB_WIND_ARCHER_2);
    lua_setfield(L, -2, "WIND_ARCHER_2");
    lua_pushinteger(L, JOB_WIND_ARCHER_3);
    lua_setfield(L, -2, "WIND_ARCHER_3");
    lua_pushinteger(L, JOB_NIGHT_WALKER);
    lua_setfield(L, -2, "NIGHT_WALKER");
    lua_pushinteger(L, JOB_NIGHT_WALKER_1);
    lua_setfield(L, -2, "NIGHT_WALKER_1");
    lua_pushinteger(L, JOB_NIGHT_WALKER_2);
    lua_setfield(L, -2, "NIGHT_WALKER_2");
    lua_pushinteger(L, JOB_NIGHT_WALKER_3);
    lua_setfield(L, -2, "NIGHT_WALKER_3");
    lua_pushinteger(L, JOB_THUNDER_BREAKER);
    lua_setfield(L, -2, "THUNDER_BREAKER");
    lua_pushinteger(L, JOB_THUNDER_BREAKER_1);
    lua_setfield(L, -2, "THUNDER_BREAKER_1");
    lua_pushinteger(L, JOB_THUNDER_BREAKER_2);
    lua_setfield(L, -2, "THUNDER_BREAKER_2");
    lua_pushinteger(L, JOB_THUNDER_BREAKER_3);
    lua_setfield(L, -2, "THUNDER_BREAKER_3");
    lua_pushinteger(L, JOB_LEGEND);
    lua_setfield(L, -2, "LEGEND");
    lua_pushinteger(L, JOB_EVAN);
    lua_setfield(L, -2, "EVAN");
    lua_pushinteger(L, JOB_ARAN);
    lua_setfield(L, -2, "ARAN");
    lua_pushinteger(L, JOB_ARAN_1);
    lua_setfield(L, -2, "ARAN_1");
    lua_pushinteger(L, JOB_ARAN_2);
    lua_setfield(L, -2, "ARAN_2");
    lua_pushinteger(L, JOB_ARAN_3);
    lua_setfield(L, -2, "ARAN_3");
    lua_pushinteger(L, JOB_EVAN_1);
    lua_setfield(L, -2, "EVAN_1");
    lua_pushinteger(L, JOB_EVAN_2);
    lua_setfield(L, -2, "EVAN_2");
    lua_pushinteger(L, JOB_EVAN_3);
    lua_setfield(L, -2, "EVAN_3");
    lua_pushinteger(L, JOB_EVAN_4);
    lua_setfield(L, -2, "EVAN_4");
    lua_pushinteger(L, JOB_EVAN_5);
    lua_setfield(L, -2, "EVAN_5");
    lua_pushinteger(L, JOB_EVAN_6);
    lua_setfield(L, -2, "EVAN_6");
    lua_pushinteger(L, JOB_EVAN_7);
    lua_setfield(L, -2, "EVAN_7");
    lua_pushinteger(L, JOB_EVAN_8);
    lua_setfield(L, -2, "EVAN_8");
    lua_pushinteger(L, JOB_EVAN_9);
    lua_setfield(L, -2, "EVAN_9");
    lua_pushinteger(L, JOB_EVAN_10);
    lua_setfield(L, -2, "EVAN_10");
}
